# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: "3"
services:
  # Python
  app:
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env

  docs:
    build:
      context: .
      dockerfile: provision/docker/docs/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env
